/*
		This file has been auto-generated by WebbotLib tools V1.1
				** DO NOT MODIFY BY HAND **
*/
#ifndef _LIB_CTOR_H_
#define _LIB_CTOR_H_
extern StatusLed statusLed;
extern Switch button;
extern Marquee marquee;
extern Servo servo1;
extern Servo servo2;
extern ServoDriver bank1;
extern UartHW uart1;
#endif
